### ISSUE TITLE
After installing ABSP, clicking on the Run app will prevent it from running

### ISSUE THREAD

**Issue by Fsrgsr** [ABSP-methylation-tool/ABSP#1]
Listening on http://127.0.0.1:5131
Warning: Error in if: Parameter length is 0
  45: observe [D:\ABSP-1.2.1/app.R#872]
  44: <observer>
   1: shiny::runApp

**Comment by MarieDenoulet** [comment]
Issue resolved in the new release v1.2.2

**Comment by Fsrgsr** [comment]
Thank you very much for squeezing out valuable time for your team to solve my problem!


晚点喝可乐
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ABSP-methylation-tool/ABSP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月6日(星期六) 晚上9:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ABSP-methylation-tool/ABSP] After installing ABSP, clicking on the Run app will prevent it from running (Issue #1)





 
Issue resolved in the new release v1.2.2
